version: "3.9"
services:
  app:
    bot:
      context: ./
      dockerfile: ./Dockerfile.bot
    container_name: bot_container
    restart: always
    networks:
      - custom

  tg_spam_plugin:
    build:
      context: ./
      dockerfile: ./Dockerfile.tg-spam-plugin
    container_name: tg_spam_plugin_container
    restart: always
    networks:
      - custom

  tg_track_stories_plugin:
    build:
      context: ./
      dockerfile: ./Dockerfile.tg-track-stories
    container_name: tg_track_stories_plugin_container
    restart: always
    networks:
      - custom

  inst_spam_plugin:
    build:
      context: ./
      dockerfile: ./Dockerfile.inst-spam-plugin
    container_name: inst_spam_plugin_container
    restart: always
    networks:
      - custom

networks:
  custom:
    driver: bridge
